### ISSUE TITLE
Got some issue when running 'Plasma-Cash-SideChain'

### ISSUE THREAD

**Issue by winar-jin** [epord/Plasma-Cash-SideChain#2]
Hi, there

By following the README file in the repo, I got everything great until '`truffle migrate` - En el repo Plasma-Cash-RootChain'  at line 19 of README.

* First,  for this side chain project,  there doesn't have any migration file in this repository. So this command just tells me that there doesn't find any migration file yet. Is this does matter?

* Sorry, I just can't understand [- En el repo Plasma-Cash-RootChain], the second part of line 19 in README file. Could you please give me some specific wording to descript the intention here.

By the way, at line 20, there says [`Go to Remix and paste all the liteInterfaces (Remove the I from the beggining of their names)`]. So what's 'liteInterfaces' here, So don't see any liteInterfaces in the code.

This is an absolutely great repo to demonstrate Plasma with Ethereum, Sincerely thank you for doing this repo. 

Thank you with best regards.

**Comment by jcaracciolo** [comment]
Hey, thanks for the issue. As you can tell this is a very WIP project we are heavingly modifying at the time. Up to last week, we didnt have a working MVP to run. So that's why the code is a little bit disorganized and the READMEs are not updated. I have updated the README now. Make sure to check out the other 2 repos that are part of this project

[API Side Chain](https://github.com/epord/Plasma-Cash-SideChain)
[Front End Client]( https://github.com/epord/CryptoMons-client)
[Ethereum Contracts](https://github.com/epord/Plasma-Cash-RootChain)

If you are still having issues please let us know, as there is still some things that are not as reliable as we want them to be.

**Comment by winar-jin** [comment]
Hi,  thank you for your warmly reply.

I had got your update of each repo. And I run `API side chain` and `Ethereum Contracts` successfully. 

After I run `Front end client`, I can load all contracts, it is great. But maybe I lost some context of what CryptoMon want to do, so I can not `Verify token history` or `Buy CryptoMon` or `Hacks`. If possible could you please send me some link or context about what  `CryptoMon` want to do, I will appreciate that. 

But it is ok and it is great, I know it is WIP. Thank you all the same.

**Comment by winar-jin** [comment]
Hi, thank you for your warmly reply.

I had got your idea. I had run this project. And know the scope of these three project. 

That's a greate project. It will be better if you could continue to finish this. That will be awesome. 

As for this issue, I think i had got my answer. I will close this issue.

Thank you all the same. 

Best regards.
